--- 
steps: 
  - 
    args: 
      - init
    name: hashicorp/terraform
  - 
    args: 
      - plan
      - "-out=terraform.tfplan"
    name: hashicorp/terraform
    volumes: 
      - 
        name: vol1
        path: /persistent_volume
  - 
    args: 
      - show
      - "-json"
      - terraform.tfplan
      - "|tee" 
      - gs://terraform-leszek/terraform.json
    name: hashicorp/terraform
    volumes: 
      - 
        name: vol1
        path: /persistent_volume
  - 
    args: 
      - convert
      - "gs://terraform-leszek/terraform.json"
    name: gcr.io/leszek-jinx-main/terraform-validator
    volumes: 
      - 
        name: vol1
        path: /persistent_volume
