steps:
- name: 'hashicorp/terraform'
  args: ['init']
- name: 'hashicorp/terraform'
  args: ['plan','-out=terraform.tfplan']
  args: ['show','-json ./tfplan.tfplan > ./tfplan.json']
- name: 'gcr.io/leszek-jinx-main/terraform-validator'
  args: ['convert','terraform.json']
