steps:
- name: 'hashicorp/terraform'
  args: ['init']
- name: 'hashicorp/terraform'
  args: ['plan','-out=terraform.tfplan']
- name: 'hashicorp/terraform'
  entrypoint: "/bin/bash"
  args: ['-c', 'show -json terraform.plan > terraform.json']
  dir: deployments/app1/dev
- name: 'gcr.io/leszek-jinx-main/terraform-validator'
  args: ['convert','terraform.json']
