steps:
- name: 'hashicorp/terraform'
  args: ['init']
- name: 'hashicorp/terraform'
  args: ['plan -out=terraform.tfplan']
- name: 'gcr.io/leszek-jinx-main/terraform-validator'
  args: ['convert terraform.tfplan']
