steps:
  - args:
      - init
    name: hashicorp/terraform
  - args:
      - plan
      - '-out=terraform.tfplan'
    name: hashicorp/terraform
  - args:
      - show
      - '-json'
      - 'terraform.tfplan'
      - '|tee /persistent_volume/terraform.json'
    name: hashicorp/terraform
  - args:
      - convert
      - /persistent_volume/terraform.json
    name: gcr.io/leszek-jinx-main/terraform-validator
