steps:
 volumes:
  - name: 'vol1'
    path: '/persistent_volume'
  - args:
      - init
    name: hashicorp/terraform
  - args:
      - plan
      - '-out=terraform.tfplan'
    name: hashicorp/terraform
  - args:
      - show
      - '-json'
      - 'terraform.tfplan'
      - '|tee /vol1/terraform.json'
    name: hashicorp/terraform
  - args:
      - convert
      - '/vol1/terraform.json'
    name: gcr.io/leszek-jinx-main/terraform-validator
